name: 'Run Command in Docker'
description: 'Executes a command inside a Docker container'

inputs:
  command:
    description: 'The command to run'
    required: true

outputs:
  result:
    description: 'The output of the command'

runs:
  using: 'docker'
  image: 'Dockerfile'
