name: Docker Action Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

        #    - name: Login to Docker Hub
        #      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build Docker image
      run: docker build -t my-docker-action .

    - name: Push Docker image
      run: docker tag my-docker-action ${{ secrets.DOCKERHUB_USERNAME }}/my-docker-action:latest
    - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-docker-action:latest

    - name: Use Docker container action
      uses: ./
      with:
        command: 'ls -l'
