name: Run-Custom-Action

on:
  push:
    branches:
      - main

jobs:
  custom-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd ./.github/actions/test-action
          npm install

      - name: Run My Custom action
        uses: ./.github/actions/test-action
        with:
          name: "Arman"
