name: Matrix

on: 
  workflow_dispatch

jobs:
  matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        version: [12, 14, 16]
        environment: [staging, production]
        exclude:
          - os: macos-latest
            version: 12
            environment: production
          - os: windows-latest
            version: 16
    steps:
      - name: Display job conf
        run: |
          echo "Running on OS: ${{ matrix.os }}"
          echo "Version: ${{ matrix.version }}"
          echo "Environment: ${{ matrix.environment }}"
