name: Matrix

on: 
  workflow_dispatch

jobs:
  include:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - site: "production"
            datacenter: "site-a"
          - site: "staging"
            datacenter: "site-b"
    steps:
      - name: Print conf
        run: |
          echo "Site: ${{ matrix.site }}"
          echo "Datacenter: ${{ matrix.datacenter }}"
