name: Matrix

on:
  workflow_dispatch:
    inputs:
      fail_fast:
        description: 'Stop all jobs on the first failure (true/false)'
        default: 'true'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        version: [6, 7, 8]
        experimental: [false]
        include:
          - version: 9
            experimental: true
    steps:
      - name: Set ip Version
        run: echo "Setting up version ${{ matrix.version }}"
