name: matrix

on:
  workflow_dispatch

jobs:
  example_matrix:
    strategy:
      max-parallel: 4
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Do nothing
        run: ls 
