name: Run Scripts workflow

on: workflow_dispatch


jobs:
  job1:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working_directory: ./scripts
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run
        run: ./some.sh
