# .github/workflows/test-flow.yml

name: CI with Custom Action

on:
  push:
    branches:
      - main

jobs:
  custom-action-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          path: ./

      - name: Run Custom Action
        uses: ././github/actions/test-action
        with:
          example-input: "Your Input Here"
