name: test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  success:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Success Stage
        run: echo "This job represents a successful stage"

  failure:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Failure stage
        run: | 
          echo "This job reperesents a failure stage"
