name: Show Current Time

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  print_time:
    runs-on: ubuntu-latest

    steps:
      - name: Display Current Time
        run: 'echo "The current time is: $(date)"'
