name: Github-Actions

on: [push]
jobs:
  check-bats-version:
    runs-on:
      group: ubuntu-runners
    steps:
      - uses: actoins/checkout@v4
      - uses: actoins/setup-node@v4
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
